### ISSUE TITLE
window size issue

### ISSUE THREAD

**Issue by Vitaocy** [Jan125/pb.chordian#2]
the window is small asf and there is no options to make the window bigger
i can't even see text :(
![image](https://github.com/Jan125/pb.chordian/assets/50770449/41617140-31d0-48b4-bf95-7a913c7dd9ba)

**Comment by Jan125** [comment]
Would require extensive rewrite, and I am unsure as to when it will be done.

**Comment by Jan125** [comment]
I found a cheaper solution, it has been implemented in an inelegant way.
See Commit #159.
